### ISSUE TITLE
the api doc link unavailable 

### ISSUE THREAD

**Issue by ChinaLewisLiu** [resiprocate/resiprocate#222] opened 2022-03-23 23:29 UTC
the api doc (http://svn.resiprocate.org/dox/)  is unavailable now,  could anyone help fix it .

**Comment by sgodin** [comment] 2022-03-24 19:31
Duplicate of issue 161:  https://github.com/resiprocate/resiprocate/issues/161

**Closed by sgodin** 2022-03-24 19:31 UTC
